name: Check Job Status

on:
    workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Job 1 Step 1"
      - name: Step 2
        run: echo "Job 1 Step 2"
      - name: Step 3
        run: echo "Job 1 Step 3"
    outputs:
      status: ${{ job.status }}

  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Job 2 Step 1"
      - name: Step 2
        run: echo "Job 2 Step 2"
      - name: Step 3
        run: echo "Job 2 Step 3"
    outputs:
      status: ${{ job.status }}

  job-3:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Download artifacts
          uses: actions/download-artifact@v2
          with:
            name: build-artifacts
        - name: Deploy to S3 bucket
          uses: jakejarvis/s3-sync-action@v0.5.0
          with:
            args: --acl public-read --delete
          env:
            AWS_S3_BUCKET: my-bucket-name
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    outputs:
        status: ${{ job.status }}

  check-job-status:
    runs-on: ubuntu-latest
    needs: [job-1, job-2, job-3]
    steps:
      - name: Check Job Status
        run: |
          if [ "${{ jobs.job-1.outputs.status }}" = "success" ] &&
             [ "${{ jobs.job-2.outputs.status }}" = "success" ] &&
             [ "${{ jobs.job-3.outputs.status }}" = "success" ]; then
            echo "All jobs succeeded"
          else
            echo "One or more jobs failed"
          fi
