name: Check Job Status

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "This is job 1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Job 2
        run: echo "This is job 2"

  check-status:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - name: show conclusion 2
        run: echo ${{ env.WORKFLOW_CONCLUSION }}
