name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build

  test:
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test

  deploy:
    runs-on: ubuntu-latest
    # needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
      - name: Deploy to S3 bucket
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: my-bucket-name
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  notify:
    needs:
      - build
      - test
      - deploy

    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: send notification if success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_ICON: https://github.com/rtCamp.png?size=48
            SLACK_CHANNEL: githubactions-poc
            SLACK_COLOR: ${{ job.status }}
            SLACK_MESSAGE: 'The pipeline Is Completed Successfully'
            SLACK_TITLE: React Project CI/CD
            SLACK_USERNAME: gaurav.talele
            SLACK_WEBHOOK: https://hooks.slack.com/services/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
        with:
            status: 'success'
            message: 'The build and deploy job succeeded'
            channel: githubactions-poc

      - name: send notification if failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_ICON: https://github.com/rtCamp.png?size=48
            SLACK_CHANNEL: githubactions-poc
            SLACK_COLOR: ${{ job.status }}
            SLACK_MESSAGE: 'The pipeline Is NOT Completed Successfully'
            SLACK_TITLE: React Project CI/CD
            SLACK_USERNAME: gaurav.talele
            SLACK_WEBHOOK: https://hooks.slack.com/services/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
        with:
            status: 'failure'
            message: 'The build and deploy job not succeeded'
            channel: githubactions-poc


    #   - name: Slack Notification
    #     uses: rtCamp/action-slack-notify@v2
    #     env:
    #       SLACK_ICON: https://github.com/rtCamp.png?size=48
    #       SLACK_CHANNEL: githubactions-poc
    #       SLACK_COLOR: ${{ job.status }}
    #       SLACK_MESSAGE: 'The pipeline Is Completed Successfully'
    #       SLACK_TITLE: React Project CI/CD
    #       SLACK_USERNAME: gaurav.talele
    #       SLACK_WEBHOOK: https://hooks.slack.com/services/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
