name: SlackNotification

on: workflow_dispatch

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{ job.status }}
        uses: rtCamp/action-slack-notify@v2.2.0
        with:
          status: ${{ job.status }}
          SLACK_CHANNEL: githubactions-poc
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: rtCamp
          fields: repository,commit,author,action,eventName,workflow,ref